#!/usr/bin/env node
/**
 * foresight-engine.mjs — v0.2
 * Reads patterns from markdown, generates foresights by context matching.
 */

import { readFileSync, existsSync, readdirSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { homedir } from "os";

const HABIT_DIR = join(homedir(), ".codex-habit");
const PAT_ACTIVE = join(HABIT_DIR, "patterns", "active");
const PROFILE_DIR = join(HABIT_DIR, "profile");
const FORESIGHTS_FILE = join(PROFILE_DIR, "foresights.md");

function readPatterns() {
  if (!existsSync(PAT_ACTIVE)) return [];
  return readdirSync(PAT_ACTIVE).filter(f => f.endsWith(".md")).map(f => {
    try {
      const text = readFileSync(join(PAT_ACTIVE, f), "utf-8");
      const m = text.match(/^---\n([\s\S]*?)\n---/);
      if (!m) return null;
      const meta = {};
      for (const line of m[1].split("\n")) {
        const i = line.indexOf(": ");
        if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 2).trim();
      }
      return meta;
    } catch { return null; }
  }).filter(Boolean);
}

function matchPattern(context, patterns) {
  const ctx = (context || "").toLowerCase();
  const results = [];
  for (const p of patterns) {
    const trigger = (p.trigger || "").toLowerCase();
    const action = (p.action || "").toLowerCase();
    const words = trigger.split(/\s+/);
    const match = words.filter(w => ctx.includes(w)).length;
    const ratio = words.length > 0 ? match / words.length : 0;
    const conf = parseFloat(p.confidence || "0") || 0;
    if (ratio > 0 && conf > 0.15) {
      results.push({
        trigger: p.trigger, action: p.action, confidence: conf,
        score: ratio * 0.6 + conf * 0.4, id: p.id
      });
    }
  }
  return results.sort((a, b) => b.score - a.score).slice(0, 10);
}

function saveForesights(list) {
  if (!existsSync(PROFILE_DIR)) mkdirSync(PROFILE_DIR, { recursive: true });
  const lines = [
    "# Foresights - Predictive Memory",
    "> Auto-generated by Codex Habit Resonance Kernel",
    "> Last updated: " + new Date().toISOString(),
    "> Patterns consulted: " + list.length,
    "",
  ];
  for (const f of list) {
    lines.push("## Foresight: " + (f.trigger || "(pattern)").slice(0, 40) + "...");
    lines.push("");
    lines.push("- **Pattern:** " + f.trigger);
    lines.push("- **Suggestion:** " + f.action);
    lines.push("- **Confidence:** " + Math.round(f.confidence * 100) + "%");
    lines.push("");
  }
  if (list.length === 0) lines.push("_No foresights yet._");
  writeFileSync(FORESIGHTS_FILE, lines.join("\n"));
}

function allForesights(patterns) {
  return patterns.filter(p => {
    const c = parseFloat(p.confidence || "0");
    return c > 0.2;
  }).slice(0, 10).map(p => ({
    trigger: p.trigger, action: p.action,
    confidence: parseFloat(p.confidence || "0")
  }));
}

const arg = process.argv[2];
if (arg === "--all") {
  const pats = readPatterns();
  const fores = allForesights(pats);
  saveForesights(fores);
  console.log(JSON.stringify({ status: "ok", foresights: fores.length }));
} else {
  let input = "";
  process.stdin.on("data", c => input += c);
  process.stdin.on("end", () => {
    try {
      const ctx = input ? JSON.parse(input).context || input : "general";
      const pats = readPatterns();
      const matched = matchPattern(ctx, pats);
      saveForesights(matched);
      console.log(JSON.stringify({ status: "ok", matched: matched.length }));
    } catch (e) {
      console.error(JSON.stringify({ error: e.message }));
    }
  });
}
